import type { StarWarsSagaSnapshot } from './star-wars-saga';

export const starWarsSagaCharacterVersionExample = {
  characterId: '665000000000000000000001',
  gameSystemId: '665000000000000000000002',
  versionNumber: 1,
  status: 'published',
  changeSummary: 'Ficha inicial de exemplo para Star Wars Saga Edition.',
  createdBy: 'example-owner',
  publishedAt: '2026-06-08T00:00:00.000Z',
  snapshot: {
    identity: {
      characterName: 'Kalen Voss',
      playerName: 'Jogador Exemplo',
      campaignName: 'Ecos da Rebeliao',
      era: 'rebellion-era',
      destiny: 'Resgate',
      gender: 'Masculino',
      age: '24',
      height: '1,78m',
      weight: '76kg',
      eyes: 'Castanhos',
      hair: 'Preto',
      skin: 'Clara',
      homeworld: 'Corellia',
      background: 'Contrabandista sensivel a Forca.',
      personality: 'Curioso, impulsivo e leal.',
      appearance: 'Jaqueta gasta, coldre baixo e olhar atento.',
      portraitUrl: '',
      notes: '',
    },
    species: { slug: 'humano' },
    abilities: {
      strength: { baseValue: 12, speciesModifier: 0, levelModifier: 0, temporaryModifier: 0 },
      dexterity: { baseValue: 14, speciesModifier: 0, levelModifier: 0, temporaryModifier: 0 },
      constitution: { baseValue: 12, speciesModifier: 0, levelModifier: 0, temporaryModifier: 0 },
      intelligence: { baseValue: 13, speciesModifier: 0, levelModifier: 0, temporaryModifier: 0 },
      wisdom: { baseValue: 10, speciesModifier: 0, levelModifier: 0, temporaryModifier: 0 },
      charisma: { baseValue: 14, speciesModifier: 0, levelModifier: 0, temporaryModifier: 0 },
    },
    classes: {
      levels: [{ classSlug: 'fora-da-lei', classType: 'heroic', level: 1, acquisitionOrder: 1 }],
      classDefenseBonuses: { reflex: 0, fortitude: 0, will: 0 },
    },
    combat: {
      hitPoints: { current: 18, maximum: 18, temporary: 0, damageTaken: 0 },
      conditionTrack: { currentStep: 0, modifiers: 0 },
      defenses: {
        reflex: { baseValue: 10, heroicLevelBonus: 0, classBonus: 0, abilityModifier: 0, equipmentBonus: 0, miscellaneousBonus: 0, temporaryBonus: 0 },
        fortitude: { baseValue: 10, heroicLevelBonus: 0, classBonus: 0, abilityModifier: 0, equipmentBonus: 0, miscellaneousBonus: 0, temporaryBonus: 0 },
        will: { baseValue: 10, heroicLevelBonus: 0, classBonus: 0, abilityModifier: 0, equipmentBonus: 0, miscellaneousBonus: 0, temporaryBonus: 0 },
      },
      speed: 6,
      destinyPoints: 1,
      forcePoints: 5,
      darkSideScore: 0,
    },
    skills: [
      { skillSlug: 'iniciativa', trained: true, focused: false, armorPenalty: 0, miscellaneousBonus: 0, temporaryBonus: 0 },
      { skillSlug: 'percepcao', trained: false, focused: false, armorPenalty: 0, miscellaneousBonus: 0, temporaryBonus: 0 },
      { skillSlug: 'usar-a-forca', trained: true, focused: false, armorPenalty: 0, miscellaneousBonus: 0, temporaryBonus: 0 },
    ],
    feats: [{ featSlug: 'sensitivo-a-forca', acquiredAtLevel: 1, source: 'level' }],
    talents: [{ talentSlug: 'ataque-furtivo', acquiredAtLevel: 1, sourceClass: 'fora-da-lei', sourceTree: 'infortunio' }],
    force: {
      forceSensitivity: true,
      forcePoints: 5,
      destinyPoints: 1,
      darkSideScore: 0,
      forcePowers: [{ powerSlug: 'truque-mental', selectedCount: 1, used: 0 }],
      forceTechniques: [],
      forceSecrets: [],
    },
    equipment: {
      inventory: [{ equipmentSlug: 'pistola-blaster', quantity: 1, equipped: true }],
      equippedWeapons: [{ slug: 'pistola-blaster' }],
      credits: 500,
      notes: '',
    },
    vehicles: { ownedVehicles: [], pilotNotes: '' },
    droid: { droidSystems: [], installedEquipment: [], modifications: [] },
    progressionLog: [],
    levelUpChoices: [],
    xpHistory: [{ amount: 0, reason: 'Criacao do personagem', createdAt: '2026-06-08T00:00:00.000Z' }],
    notes: '',
  } satisfies StarWarsSagaSnapshot,
};
